# Generated by Django 5.1.3 on 2024-11-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerStartDate', models.DateField()),
                ('offerEndDate', models.DateField()),
                ('offerReason', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
